### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_getter'

### ISSUE THREAD

**Issue by hadim** [cloudspannerecosystem/python-spanner-sqlalchemy#107]
Here is an error that seems is hard to reproduce. I think it happens when too many requests are made on a Spanner database and some of them are not satisfied because of resource constraints.

I am using SQLAlchemy 1.3.23.

Here is a full traceback:

```
"""
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 779, in _getter
    getter = self._metadata._getter
AttributeError: 'NoneType' object has no attribute '_getter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
# .......
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 58, in instances
    *[
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 59, in <listcomp>
    query_entity.row_processor(query, context, cursor)
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 4422, in row_processor
    _instance = loading._instance_processor(
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 421, in _instance_processor
    getter = result._getter(col, False)
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 781, in _getter
    return self._non_result(None, err)
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1236, in _non_result
    util.raise_(
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
"""
```

It happens when doing 1,000 calls in parallel with `n_jobs=16` (every call is reading ~1k-5k rows). And the spanner DB has 3 nodes.

Do you think this is indeed due to resource constraints on the DB side and so there is nothing to do besides increasing the number of nodes? Or is it another bug that can actually be addressed here?

**Comment by hadim** [comment]
An easy fix is just to catch the error:

```
try:
    rows = query.all()
except sa.exc.ResourceClosedError:
    rows = None
```

It works fine but I still don't know whether I am missing some rows here or whether a given request is just returning no rows because no rows exist in the database.

I tried to reproduce it but sending a single SQL request that I know will return 0 rows and I don't see the bug. It only seems to happen when executing many requests in parallel with `joblib` and `loky`.

**Comment by hadim** [comment]
Checking again and the requests that throw the error contain a `WHERE` statement that should indeed return rows so catching the error is probably not the good thing to do here.

**Comment by hadim** [comment]
After more investigations, it turns out the error is due to a closed connection. Probably because of a timeout.

Using `NullPool` fixes it (increasing the timeout of a `QueuePool` might work too).

```python
sa.create_engine(db_url, poolclass=sa.pool.NullPool)
```

Hope it can help someone!

**Comment by hadim** [comment]
I am not going to reopen here but I still see the error from time to time, but its frequency is much lower than before while not much has changed in the workload source code and the Spanner DB.

So I am a bit confused. I will keep monitoring it and report here.
